version: 2

phantomjs: &phantomjs
  steps:
    # Restore PhantomJs
    - restore_cache:
        key: v1.1-phantomjs-2.1.1

    - run:
        name: Install phantomjs
        command: |
          if ! [ $(which phantomjs) ]; then
            sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
          fi
          sudo chmod ugo+x /usr/local/bin/phantomjs

    - save_cache:
        key: v1.1-phantomjs-2.1.1
        paths:
          - /usr/local/bin/phantomjs


buildtest: &buildtest
  working_directory: ~/repo
  steps:
    - checkout

    # Restore npm modules
    - restore_cache:
        keys:
          - dependency-cache-{{ checksum "package.json" }}
          - v1.1-phantomjs-2.1.1

    - run:
        name: NPM Install
        command: npm install

    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules

    - run:
        name: Create directories for xunit reports
        command: |
          mkdir -p ~/reports/mocha
          mkdir -p ~/reports/browser
          mkdir -p ~/reports/a11y

    - run:
        name: Run Mocha unit tests
        command: |
          npm run test-unit-ci
        environment:
          XUNIT_FILE: ~/reports/mocha/unit.xml
        when: always

    # XXX this is a workaround for a bug in WebDriverIO
    # that doesn't allow for absolute paths in the xunit
    # output directory:
    # <https://github.com/webdriverio/webdriverio/issues/926>
    - run:
        name: WebDriverIO workaround directory
        command: |
          ln -s /tmp

    - run:
        name: Wait for Federalist Build
        command: ./test/ci.sh

    - run:
        name: Run Browser tests
        command: npm run test-ci

    - run:
        name: Run A11y tests
        command: npm run test-a11y

    - store_test_results:
        paths:
          - ~/reports/mocha
          - ~/reports/browser
          - ~/reports/a11y

jobs:
  install_phantomjs:
    <<: *phantomjs
    docker:
      - image: circleci/node:4.8

  build_and_test:
    <<: *buildtest
    docker:
      - image: circleci/node:4.8
        environment:
          TEST_REPORTS_CI: ~/reports

workflows:
  version: 2
  build:
    jobs:
      - install_phantomjs
      - build_and_test:
          requires:
            - install_phantomjs
